name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Continue de fonctionner sur `main`
    tags:
      - 'v*'  # Déclenche le workflow lors d'un tag versionné (ex: v0.0.1, v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          cd app
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          cd ..

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sumot:${{ env.VERSION }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/sumot:${{ env.VERSION }}

      - name: Update Deployment Repo
        run: |
          git clone https://github.com/marcderoo/SUMOT-deployment.git
          cd SUMOT-deployment

          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/sumot:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/sumot:${{ env.VERSION }}|g" deployment/deployment.yml

          sudo apt-get install -y yq
          TIMESTAMP=$(date +%s)
          yq -y -i ".metadata.annotations.timestamp = \"$TIMESTAMP\"" deployment/deployment.yml

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add deployment/deployment.yml
          git commit -m "Update image to version ${{ env.VERSION }}"
          git push https://x-access-token:${{ secrets.DEPLOYMENT_REPO_TOKEN }}@github.com/marcderoo/SUMOT-deployment.git main
